name: Bug Report
description: 报告一个 Bug
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你报告 Bug！请尽可能详细地填写以下信息，以便我们快速定位和修复问题。

  - type: checkboxes
    id: existing-issue
    attributes:
      label: 前置检查
      options:
        - label: 我已搜索过现有 Issue，没有发现相同问题
          required: true
        - label: 我已阅读过 README 和文档
          required: false

  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 清晰简洁地描述发生了什么
      placeholder: 当我做 xxx 时，发生了 yyy，但我期望 zzz。
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 复现步骤
      description: 如何重现此问题
      placeholder: |
        1. 打开 VS Code
        2. 编辑某个文件
        3. 将光标移到 ...
        4. 观察到 ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 预期行为
      description: 你期望发生什么？
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 实际行为
      description: 实际发生了什么？
    validations:
      required: true

  - type: input
    id: vscode-version
    attributes:
      label: VS Code 版本
      placeholder: 例如：1.87.0
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: Windows 版本
      placeholder: 例如：Windows 11 23H2
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: IME Switcher 版本
      placeholder: 例如：0.5.0
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 相关日志 / 截图
      description: 如有错误日志（"输出"面板 → "IME Switcher"）或截图，请粘贴在此
      render: text
